### ISSUE TITLE
Without noise, PGD fails to start from different initial point

### ISSUE THREAD

**Issue by joneswong** [Hadisalman/smoothing-adversarial#6]
As you can see, the attribute `self.random_start` has not been used by the PGD_L2 class. Thus, if there is no noise, say that `noise_sd=0`, then PGD will always start from the original x, rather than intended different initial points. This seems to weaken the effectiveness of PGD.

**Comment by Hadisalman** [comment]
@joneswong Apologies for the late reply. Yea we don't use random start in any of our experiments, and yup we agree you might be able to get even better results by doing random start. Though in the presence of `noise_sd`, I don't think it would change things since there is an inherent randomness already in the smoothed classifier when it is evaluated multiple at the same data point. Hope this helps!
